### ISSUE TITLE
Help: Using LibRangeCheck to pull a range variable, rather than just validating against it as a trigger

### ISSUE THREAD

**Issue by alphabitnz** [WeakAuras/LibRangeCheck-2.0#2]
Hi,

Hopefully this is self explanatory, just wanting to use the existing LibRangeCheck code as per Player/Unit Info>Range Check in such a way that I can display the range variable itself (or process with custom code) rather than dealing with the limitations of the Weakauras inbuilt Range Check trigger to generate such a variable the difficult way.

Is there any such variable or function available for this purpose already, or maybe any custom function someone has built already you might be aware of?

Thank you so much!

**Comment by InfusOnWoW** [comment]
I have no idea what you want. But this isn't a help forum. This is a issue tracker for bugs and feature requests.
